services:
  store_manager:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - labo03-network
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: labo03
      DB_PASS: labo03
      DB_NAME: labo03_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo03_db
      MYSQL_USER: labo03
      MYSQL_PASSWORD: labo03
    networks:
      - labo03-network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -ulabo03 -plabo03 labo03_db -e 'SELECT * FROM products LIMIT 1;' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - labo03-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

networks:
  labo03-network:
    driver: bridge
    external: true

volumes:
  mysql_data:
